# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_v0.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.OpenFolder = QtWidgets.QPushButton(self.centralwidget)
        self.OpenFolder.setGeometry(QtCore.QRect(20, 180, 71, 31))
        self.OpenFolder.setObjectName("OpenFolder")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(20, 150, 71, 20))
        self.checkBox.setObjectName("checkBox")
        self.BoardNo = QtWidgets.QComboBox(self.centralwidget)
        self.BoardNo.setGeometry(QtCore.QRect(20, 20, 101, 31))
        self.BoardNo.setObjectName("BoardNo")
        self.BoardNo.addItem("")
        self.BoardNo.addItem("")
        self.BoardNo.addItem("")
        self.BoardNo.addItem("")
        self.BoardNo.addItem("")
        self.RecipeType = QtWidgets.QComboBox(self.centralwidget)
        self.RecipeType.setGeometry(QtCore.QRect(20, 60, 101, 31))
        self.RecipeType.setObjectName("RecipeType")
        self.SubType = QtWidgets.QComboBox(self.centralwidget)
        self.SubType.setGeometry(QtCore.QRect(20, 100, 101, 31))
        self.SubType.setObjectName("SubType")
        self.BackupFileList = QtWidgets.QComboBox(self.centralwidget)
        self.BackupFileList.setGeometry(QtCore.QRect(100, 140, 101, 31))
        self.BackupFileList.setObjectName("BackupFileList")
        self.Readout = QtWidgets.QPushButton(self.centralwidget)
        self.Readout.setGeometry(QtCore.QRect(20, 220, 71, 31))
        self.Readout.setObjectName("Readout")
        self.Import = QtWidgets.QPushButton(self.centralwidget)
        self.Import.setGeometry(QtCore.QRect(100, 180, 71, 31))
        self.Import.setObjectName("Import")
        self.Export = QtWidgets.QPushButton(self.centralwidget)
        self.Export.setGeometry(QtCore.QRect(100, 220, 71, 31))
        self.Export.setObjectName("Export")
        self.Download = QtWidgets.QPushButton(self.centralwidget)
        self.Download.setGeometry(QtCore.QRect(180, 220, 71, 31))
        self.Download.setObjectName("Download")
        self.Upload = QtWidgets.QPushButton(self.centralwidget)
        self.Upload.setGeometry(QtCore.QRect(180, 180, 71, 31))
        self.Upload.setObjectName("Upload")
        self.ReadoutTable = QtWidgets.QColumnView(self.centralwidget)
        self.ReadoutTable.setGeometry(QtCore.QRect(20, 340, 531, 181))
        self.ReadoutTable.setObjectName("ReadoutTable")
        self.Log = QtWidgets.QTextEdit(self.centralwidget)
        self.Log.setGeometry(QtCore.QRect(350, 40, 351, 211))
        self.Log.setObjectName("Log")
        self.RecipeName = QtWidgets.QLineEdit(self.centralwidget)
        self.RecipeName.setGeometry(QtCore.QRect(20, 260, 113, 20))
        self.RecipeName.setObjectName("RecipeName")
        self.Backup = QtWidgets.QPushButton(self.centralwidget)
        self.Backup.setGeometry(QtCore.QRect(160, 260, 71, 31))
        self.Backup.setObjectName("Backup")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.OpenFolder.setText(_translate("MainWindow", "Open Folder"))
        self.checkBox.setText(_translate("MainWindow", "CheckBox"))
        self.BoardNo.setItemText(0, _translate("MainWindow", "Common"))
        self.BoardNo.setItemText(1, _translate("MainWindow", "Board-1"))
        self.BoardNo.setItemText(2, _translate("MainWindow", "Board-2"))
        self.BoardNo.setItemText(3, _translate("MainWindow", "Board-3"))
        self.BoardNo.setItemText(4, _translate("MainWindow", "Board-4"))
        self.Readout.setText(_translate("MainWindow", "Readout"))
        self.Import.setText(_translate("MainWindow", "Import"))
        self.Export.setText(_translate("MainWindow", "Export"))
        self.Download.setText(_translate("MainWindow", "Download"))
        self.Upload.setText(_translate("MainWindow", "Upload"))
        self.Backup.setText(_translate("MainWindow", "Backup"))
